language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER creez WITH PASSWORD 'password';" -U postgres
  - flask init_db

env:
  global:
    - DB_NAME=testdb
    - DB_USER=creez
    - DB_PASSWORD=password

script:
  - nosetests --with-coverage  --cover-package=app && coverage report

after_success:
  - coveralls