language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  -  CREATE TABLE requests(
        id serial PRIMARY KEY,
        public_id varchar NOT NULL UNIQUE,
        title varchar NOT NULL,
        location varchar NOT NULL,
        description text,
        user_id integer NOT NULL,
        request_type varchar NOT NULL,
        status varchar NOT NULL
  );
  - CREATE TABLE users(
      id serial PRIMARY KEY,
      username VARCHAR NOT NULL UNIQUE,
      name VARCHAR NOT NULL,
      email VARCHAR NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      is_admin BOOLEAN NOT NULL
  );

env:
  global:
    - DB_NAME=testdb
    - DB_USER=postgres

script:
  - nosetests --with-coverage  --cover-package=app && coverage report

after_success:
  - coveralls