FORMAT: 1A
HOST: https://m-tracker-app.herokuapp.com

# M-tracker

A maintenance/repair request app.
## UserSignup Collection [/api/v2/users/auth/signup/]
### Signup [POST]
+ Request (application/json)
    + Attributes (Signup Post)
    
+ Response 201 (application/json)

        + message: Account successfully created

## UserSignup Collection [/api/v2/users/auth/signin/]
### Signup [POST]
+ Request (application/json)
    + Attributes (Signin Post)
    
+ Response 201 (application/json)
    + {"access_tokenge": token}


## RequestsList Collection [/api/v2/users/requests/]
### List All Request [GET]

Get all requests
+ Response 200 (application/json)
    + Attributes (array[Request])
    
    
### Make a New Request [POST]
+ Request (application/json)
    + Attributes (Request Post)
    
+ Response 201 (application/json)
    + Attributes (Request)
            

## Request Collection [/api/v2/users/requests/{request_id}]          
### Get a Request [GET]

Get a single requests 
+ Parameters
    + request_id (number) - ID of the Request in the form of an integer
        
+ Response 200 (application/json)
    + Attributes (Request)         
            
# Data Structures
## Signup Post (object)
+ id: 2321 (number, required)
+ name: User One (string, required)
+ username: user1 (string, required)
+ password: supersecret (string, required)
+ confirm_password: supersecret (string, required)
## Signin Post (object)
+ username: user1 (string, required)
+ password: supersecret (string, required)
## Request (object)
+ id: 21323232 (number, required)
+ title: Broken Desktop (string, required)
+ user_id: 2234234 (number, required)
+ location: Some locaotion (string, required)
+ description: Some useful Description here (string)
+ public_id: sdkmhfbkjsdh (string, required)
## Request Post (object)
+ title: Broken Desktop (string, required)
+ description: Some useful Description here (string)
+ location: Some locaotion (string, required)
+ request_type: Some Type (string)
+ public_id: sdkmhfbkjsdh (string, required)